package:
  name: quicklogging
  version: "0.4"

source:
  path: .

requirements:
  build:
    - python
  run:
    - python

build:
  noarch: True
  noarch_python: True
  number: 1
  preserve_egg_dir: True
  script: python setup.py install

about:
  home: https://github.com/majerteam/quicklogging
  license: MIT
  license_file: LICENSE
